# Generated by Django 5.2.7 on 2025-10-17 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 4, 20, 31, 612217, tzinfo=datetime.timezone.utc)),
        ),
    ]
