# Generated by Django 5.2.7 on 2025-10-17 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todolist_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 31, 5, 21, 35, 293515, tzinfo=datetime.timezone.utc)),
        ),
    ]
