# Generated by Django 5.2.7 on 2025-10-19 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todolist_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 11, 2, 22, 34, 24, 590728, tzinfo=datetime.timezone.utc)),
        ),
    ]
