# Generated by Django 5.2.7 on 2025-10-24 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_todolist_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 11, 7)),
        ),
    ]
